// Pre-written OECD-quality economic commentary for all G20 economies.
// All figures drawn from World Bank Open Data, IMF DataMapper, and OECD MSTI
// as seeded in the Supabase database (2024 actuals where available).

window.G20_COMMENTARY = {

  // ── Global Outlook ───────────────────────────────────────────────────────────
  global: {
    title: 'G20 Economic Outlook, 2024 Assessment',
    cutoff: 'Data as of Q4 2024',
    paragraphs: [
      'The G20 economies posted aggregate output of approximately $97 trillion in 2024, with broadly stable aggregate growth masking a pronounced divergence in economic trajectories. Emerging market and developing economies continued to drive global expansion, led by India (7.1%), Indonesia (5.0%), and China (5.0%), while advanced economy growth remained subdued under the sustained weight of post-pandemic monetary tightening. The United States was the notable exception, recording 2.8% growth and outperforming all other G7 economies for the third consecutive year.',
      'Disinflation advanced materially across the G20 in 2024. Consumer price inflation returned to or near central bank targets in the United States (2.9%), the euro area, Canada (2.4%), and South Korea (2.3%), enabling the beginning of monetary easing cycles. The aggregate picture, however, conceals significant outliers: Argentina continued to experience a macroeconomic emergency with CPI inflation of 219.9%, Türkiye sustained elevated price pressures at 58.5% despite aggressive tightening, and Russia\'s wartime fiscal expansion pushed inflation to 8.4%. In contrast, China recorded near-deflationary conditions (0.2% CPI), reflecting weak domestic demand and structural adjustment in the property sector.',
      'Fiscal sustainability has become the defining medium-term risk for several major economies. Gross government debt exceeded 100% of GDP in seven G20 members as of 2024: Japan (214%), Italy (135%), the United States (122%), France (113%), Canada (110%), the United Kingdom (100%), and China (90%). In a higher-for-longer interest rate environment, debt-service costs are absorbing rising shares of public revenues, constraining the fiscal space available for growth-enhancing investment. Germany, with debt at 62% of GDP and a current account surplus of 5.8%, retains the greatest fiscal capacity among large advanced economies, but its second consecutive year of contraction (-0.5% in 2024) underscores the structural headwinds facing European industry.',
      'The near-term risk outlook is tilted to the downside. Escalating trade policy uncertainty, including US tariff measures and their cascading effects through global supply chains, poses a material threat to trade-dependent economies, particularly Germany, South Korea, Japan, and Mexico. Geopolitical disruptions continue to fragment energy and commodity markets. China\'s property sector adjustment remains incomplete, weighing on domestic demand and creating spillover effects across commodity exporters. On the upside, accelerating artificial intelligence adoption, green energy investment, and nearshoring-driven capital expenditure represent structural tailwinds if supported by effective policy frameworks.',
      'Structural reform priorities diverge sharply across the G20. For advanced economies, the challenge is raising potential growth through labour productivity, skills investment, and industrial modernisation while managing high debt stocks. For large emerging markets, India, Indonesia, Brazil, the imperative is channelling growth into durable human capital, infrastructure, and institutional quality gains. For commodity-dependent economies (Saudi Arabia, Russia, South Africa), diversification away from resource dependence remains the overarching structural agenda. Labour market outcomes warrant particular attention: South Africa\'s unemployment rate of 32.3% constitutes a structural emergency, while Argentina\'s economic stabilisation is imposing near-term employment costs.',
    ],
    keyRisks: [
      'US trade policy escalation and tariff spillovers on open economies',
      'China property sector adjustment: risk of sharper-than-expected slowdown',
      'Fiscal sustainability in high-debt advanced economies amid rate normalisation',
      'Geopolitical energy disruptions: Middle East and Russia-Ukraine',
      'Premature easing of monetary policy reigniting inflation in disinflation laggards',
    ],
    upside: [
      'AI-driven productivity acceleration in technology-intensive economies',
      'Faster-than-expected disinflation enabling front-loaded monetary easing',
      'Nearshoring and supply chain diversification boosting EM investment',
      'Green energy transition reducing energy import dependence in many economies',
    ],
  },

  // ── Country commentaries ─────────────────────────────────────────────────────
  countries: {

    USA: {
      headline: 'Exceptional resilience, but fiscal and external imbalances widen',
      paragraphs: [
        'The United States delivered 2.8% real GDP growth in 2024, the strongest performance among G7 economies for the third consecutive year, underpinned by robust consumer spending, tight labour markets, and sustained business investment in technology and infrastructure. GDP reached $29.3 trillion, reinforcing the United States\' position as the world\'s largest economy. Unemployment held at 4.0%, consistent with full employment, while wage growth continued to outpace inflation, supporting household purchasing power.',
        'Inflation moderated to 3.0% in 2024, approaching but not yet reaching the Federal Reserve\'s 2% target. The disinflation trajectory reflects the lagged impact of 525 basis points of tightening delivered between 2022 and 2023, although services inflation proved stickier than goods deflation. The Fed began a cautious easing cycle in the second half of 2024, reducing the federal funds rate while signalling a higher-for-longer policy stance. GDP per capita of $86,000 is the highest among all G20 economies.',
        'The fiscal position presents the most significant structural vulnerability. Gross government debt reached 122% of GDP in 2024, elevated by historical standards, and the federal deficit remained above 5% of GDP, driven by mandatory spending (Social Security, Medicare) and elevated debt-service costs. Health expenditure at 16.7% of GDP, the highest in the world by a wide margin, reflects both the cost of universal coverage gaps and the price-intensive US healthcare system. The current account deficit widened to -4.1% of GDP, reflecting strong domestic demand and the dollar\'s reserve currency status.',
        'Near-term growth is expected to moderate from 2024\'s pace as fiscal impulse fades and monetary policy remains restrictive in real terms. The primary risks are trade policy escalation, with potential tariff measures affecting import prices and global supply chains, and the absence of a credible medium-term fiscal consolidation framework. R&D investment of 3.45% of GDP, the second-highest in the G20, underpins innovation leadership, though translating this into broad-based productivity growth requires sustained human capital investment and skills upgrading.',
      ],
    },

    CHN: {
      headline: 'Growth target met, but deflation risk and property adjustment weigh',
      paragraphs: [
        'China\'s economy expanded 5.0% in 2024, precisely meeting the government\'s official growth target, though this masked significant variation across sectors. Manufacturing exports and government infrastructure investment remained the primary growth engines, while private consumption recovery was incomplete and the property sector continued its prolonged adjustment. GDP reached $18.74 trillion, consolidating China\'s position as the world\'s second-largest economy and accounting for roughly 19% of G20 aggregate output.',
        'Consumer price inflation fell to just 0.2% in 2024, the lowest in the G20, raising concerns about nascent deflationary dynamics. Weak domestic demand, excess industrial capacity, and property-sector wealth effects suppressed price formation despite policy stimulus. Producer price deflation persisted for most of the year, eroding corporate margins and investment incentives. Unemployment held at 4.6%, though youth unemployment (not captured in this aggregate) remained a policy concern. The current account surplus widened to 2.3% of GDP, reflecting suppressed import demand.',
        'Gross government debt reached an estimated 90% of GDP in 2024, understating total public sector leverage when off-balance-sheet local government financing vehicle (LGFV) obligations are included. The property sector, which at peak accounted for approximately 25% of GDP, underwent a significant contraction following the Evergrande default and broader regulatory tightening. Housing investment declined sharply, weighing on steel, cement, and household goods demand. Policy authorities deployed a combination of monetary easing, fiscal stimulus, and regulatory adjustments to stabilise conditions without fully reflating the sector.',
        'R&D investment of 2.58% of GDP, and a deepening domestic semiconductor and AI ecosystem, signals China\'s strategic intent to reduce technology dependence and advance up global value chains. The transition from investment-and-export-led growth to consumption-driven expansion remains the central structural challenge of the next decade. Near-term risks include escalating trade policy tensions with the United States and Europe, export-sector overcapacity generating bilateral trade frictions, and the possibility that property adjustment is more protracted than official projections assume.',
      ],
    },

    DEU: {
      headline: 'Second consecutive contraction signals structural de-industrialisation',
      paragraphs: [
        'Germany contracted 0.5% in 2024, its second consecutive year of negative real growth, a post-war rarity that reflects deep structural rather than merely cyclical pressures. GDP stood at $4.69 trillion, the largest in Europe, but industrial output, particularly in automotive, chemicals, and machinery, declined materially. High energy costs following the 2022 energy shock, weak global capital goods demand, and the automotive sector\'s lagged transition to electric vehicles drove the contraction. Unemployment remained low at 3.4%, reflecting Germany\'s strong short-time work (Kurzarbeit) mechanisms.',
        'Inflation moderated to 2.5% in 2024, broadly in line with the ECB target, providing the European Central Bank space to ease monetary policy. The current account surplus of 5.8% of GDP is structurally large, reflecting Germany\'s export-intensive economy and compressed domestic demand, and has been a persistent source of intra-European imbalance. Investment rates have underperformed relative to historical norms, partly reflecting uncertainty about the energy transition, regulatory burden, and geopolitical risks.',
        'Germany\'s fiscal position is comparatively strong, with gross government debt at 62% of GDP, among the lowest for a G20 advanced economy, and the Constitutional Debt Brake (Schuldenbremse) providing a legal framework for fiscal discipline. However, this fiscal conservatism has constrained public investment precisely when the economy requires transformation. R&D spending of 3.15% of GDP and a deep industrial base provide structural advantages that are at risk if investment in modernisation is delayed.',
        'The near-term outlook hinges on three structural adjustments: accelerating the energy transition to secure low-cost renewable power, transforming the automotive industry toward electrification and software-defined vehicles, and reversing the multi-year decline in business investment. A coordinated fiscal response leveraging available fiscal space, combined with EU single-market integration deepening, could stabilise recovery. The primary near-term risk is a second consecutive year of contraction if global trade volumes weaken further under escalating US tariff measures.',
      ],
    },

    JPN: {
      headline: 'Near-zero growth, but historic inflation and Bank of Japan normalisation mark a turning point',
      paragraphs: [
        'Japan\'s economy contracted 0.2% in 2024, the only contraction among the major Asian economies, constrained by weak private consumption, export softness, and yen depreciation-induced import cost pressures. GDP stood at $4.19 trillion, the third-largest in Asia and the fourth-largest globally. Despite the subdued cyclical position, 2024 marked a historic turning point: Japan sustained positive inflation (2.7% CPI) for a second consecutive year, ending the three-decade deflationary trap that had defined Japanese economic policy.',
        'The Bank of Japan cautiously normalised monetary policy in 2024, raising the policy rate from near-zero for the first time since 2008 and adjusting its yield curve control framework. This represents one of the most significant shifts in global monetary policy configuration, removing the last major central bank anchor to ultra-loose conditions. While beneficial for Japan\'s long-run monetary normalisation, the yen\'s trajectory and imported inflation dynamics complicate the near-term outlook for household real incomes.',
        'Gross government debt of 214% of GDP is the highest in the G20 by a wide margin. However, approximately 90% is domestically held, substantially moderating rollover risk compared to externally leveraged equivalents. The current account surplus of 4.7% of GDP, driven by income receipts from overseas investments rather than trade, provides meaningful external resilience. Unemployment at 2.5% reflects genuine near-full employment. R&D investment of 3.44% of GDP, second-highest in the G20, reflects Japan\'s technology-intensive industrial base in semiconductors, robotics, and advanced manufacturing.',
        'Demographic decline, Japan\'s working-age population has been contracting for two decades, remains the primary structural constraint on potential growth. Near-term priorities include sustaining the wage-price spiral that is normalising inflation, implementing structural reforms to boost female and elderly labour participation, and managing the fiscal consolidation trajectory in a rising interest rate environment. The risk of a wage-price cycle reverting to deflation if external shocks interrupt domestic demand recovery remains the most consequential downside scenario.',
      ],
    },

    IND: {
      headline: 'World\'s fastest-growing major economy, with significant investment headroom',
      paragraphs: [
        'India recorded 7.1% real GDP growth in 2024, the highest rate among all G20 economies, underpinned by strong public capital expenditure, resilient domestic consumption, and an expanding digital economy. GDP reached $3.76 trillion, consolidating India\'s position as the fifth-largest economy globally and the fastest-growing large economy for the third consecutive year. Strong performance in manufacturing, services exports (particularly IT and business process outsourcing), and infrastructure investment drove broad-based expansion.',
        'Inflation moderated to 4.6% in 2024, within the Reserve Bank of India\'s 2-6% tolerance band, as food prices stabilised and monetary policy remained restrictive. Unemployment held at 4.9%. GDP per capita of $2,785 underscores the significant development gap relative to advanced economies, India\'s impressive aggregate growth rate is partly a function of catch-up dynamics from a low base. The current account deficit narrowed to -0.8% of GDP, supported by strong services exports and remittance inflows.',
        'Government debt at 85% of GDP is elevated for a developing economy, reflecting pandemic-era fiscal expansion and the ongoing government capital expenditure push. R&D investment at 0.65% of GDP and health spending at 3.3% of GDP are the structural underinvestment areas that risk constraining the economy\'s long-run growth potential. For comparison, China spends 2.58% of GDP on R&D and 5.9% on health. Gini at 25.5 appears favourable, though this reflects data measurement challenges given the size and informality of the Indian economy.',
        'India\'s demographic dividend, a young and growing labour force, provides a structural tailwind unavailable to aging advanced economies, but translating this into productivity requires quality education, skills training, and formal sector job creation. The near-term outlook is favourable, with projections of continued 6-7% growth supported by government investment, manufacturing diversification (including nearshoring from China), and digital infrastructure expansion. Key risks include climate-related agricultural shocks, geopolitical supply chain disruptions affecting oil imports, and fiscal sustainability if growth disappoints.',
      ],
    },

    GBR: {
      headline: 'Recovery underway but structural productivity and fiscal constraints persist',
      paragraphs: [
        'The United Kingdom returned to modest growth of 1.1% in 2024, recovering from near-stagnation in 2023. GDP reached $3.69 trillion, the sixth-largest globally. Growth was primarily services-led, with consumer spending recovering as real wage growth resumed following the 2022-2023 cost-of-living crisis. However, business investment and goods-producing sectors remained subdued, reflecting structural uncertainty and the ongoing adjustment of UK-EU trade relationships following Brexit.',
        'Inflation remained above target at 3.3% in 2024, higher than Germany (2.3%), France (2.0%), and Italy (1.0%), reflecting stickier services inflation and persistent wage pressures in a tight labour market. Unemployment held at 4.4%. The Bank of England began a cautious easing cycle but maintained a restrictive policy stance. Health spending at 11.1% of GDP and R&D at 2.68% are broadly in line with European peers, though below the UK\'s pre-Brexit trajectory.',
        'Government debt reached 100% of GDP in 2024, a post-war milestone, while the current account deficit of -3.0% of GDP reflects structural trade imbalances and income outflows. The new government\'s October 2024 budget signalled a modest expansion of public investment, partly funded by borrowing and tax increases, within a redrawn fiscal framework. GDP per capita of $53,000 reflects a high-income economy, though UK productivity growth has underperformed relative to US and continental European peers for over a decade.',
        'Medium-term growth prospects hinge on resolving the UK\'s structural productivity puzzle, a combination of skills gaps, investment shortfalls, and trade fragmentation from EU exit. Near-term risks include a re-escalation of inflationary pressures if services wages remain elevated, fiscal consolidation pressure constraining public investment, and vulnerability to US trade policy shifts given deep transatlantic economic ties. The UK\'s strong financial services sector and established innovation ecosystem in life sciences and fintech provide genuine structural strengths.',
      ],
    },

    FRA: {
      headline: 'Moderate recovery, fiscal consolidation imperative, and political uncertainty',
      paragraphs: [
        'France expanded 1.2% in 2024, a moderate recovery reflecting resilient household consumption, tourism, and services exports. GDP reached $3.16 trillion. The economy displayed relative resilience compared to Germany, benefiting from lower energy intensity, greater service-sector weight, and the dampening effect of the eurozone\'s single currency on competitiveness shocks. Public sector employment, among the largest in the OECD relative to economy size, provided a stabilising buffer through the cycle.',
        'Inflation fell to 2.0% in 2024, broadly in line with the ECB\'s 2% target and among the lowest in the G20, reflecting the euro area\'s success in anchoring price expectations following the 2021-2023 inflation shock. Unemployment at 7.4% remains the highest among the G7 large economies, reflecting persistent structural features of the French labour market including high entry-level employment costs and the role of the minimum wage (SMIC). Despite significant labour market reforms since 2017, youth unemployment and long-term unemployment remain elevated.',
        'Public debt reached 113% of GDP in 2024, triggering an EU Excessive Deficit Procedure and requiring a structural adjustment path. France\'s fiscal position worsened in 2023-2024 partly due to the withdrawal of energy price shields, but underlying primary deficits remain large. Health spending at 11.5% of GDP, the highest among the major European economies, reflects France\'s comprehensive social protection model and robust public health system. R&D at 2.18% of GDP trails Germany\'s 3.15%, though France has world-leading capabilities in aerospace, nuclear energy, and luxury goods.',
        'Political uncertainty following the 2024 legislative elections resulted in a hung parliament, complicating the passage of the fiscal consolidation measures required by the EU framework. Near-term risks include market pressure on French sovereign spreads if fiscal credibility is questioned, and the possibility that structural reforms to pensions and labour markets are reversed or stalled. Longer-term, France\'s demographic profile is more favourable than Germany\'s or Italy\'s, providing a structural growth advantage within Europe.',
      ],
    },

    ITA: {
      headline: 'Sustained debt vulnerability; growth below potential despite disinflation',
      paragraphs: [
        'Italy grew 0.7% in 2024, below the eurozone average, as weak domestic investment and subdued private consumption constrained expansion. GDP stood at $2.38 trillion. Growth was partly supported by EU Next Generation EU (NGEU) Recovery Fund transfers, which are financing infrastructure, green transition, and digitalisation projects. Tourism, a significant contributor to Italian GDP, performed strongly. However, manufacturing and export sectors faced headwinds from weak German demand and global capital goods softness.',
        'Inflation fell sharply to 1.0% in 2024, the lowest in the G20, reflecting weak domestic demand and moderating energy prices. This is well below the ECB\'s 2% target, signalling demand-side weakness. Unemployment of 6.5% has declined from post-pandemic peaks but structural features, regional disparities between north and south, high youth unemployment, and low female labour participation, persist. GDP per capita of $40,000 reflects a significant productivity and income gap versus northern European peers.',
        'Italy\'s gross government debt of 135% of GDP is the third-highest in the G20 and the primary vulnerability in the Italian economic outlook. Debt-service costs have risen with ECB rate increases, consuming a rising share of public revenues and constraining productive public investment. The current account surplus of 1.1% of GDP provides modest external balance support. Health spending at 8.4% of GDP is below the EU average, reflecting fiscal pressure, while R&D at 1.38% of GDP reflects Italy\'s concentration in traditional manufacturing sectors with lower knowledge intensity.',
        'Italy\'s growth potential remains constrained by the combination of an ageing population, the oldest in the G20 after Japan, persistent legal and administrative complexity discouraging investment, and the need for public sector efficiency improvements to unlock EU recovery transfers at scale. The near-term outlook is mildly positive, supported by NGEU disbursements and ECB easing. The primary risk remains a confidence shock to Italian sovereign bonds if fiscal consolidation stalls or if ECB normalisation raises debt refinancing costs faster than fiscal revenues can absorb.',
      ],
    },

    BRA: {
      headline: 'Strongest growth in years, but inequality, debt, and fiscal credibility remain focal',
      paragraphs: [
        'Brazil posted 3.4% real GDP growth in 2024, its strongest performance since the 2021 post-pandemic rebound, driven by a buoyant agricultural sector (record harvests of soybeans and corn), resilient household consumption supported by expanded social transfers, and strong commodity exports. GDP reached $2.19 trillion. Services and retail trade also contributed meaningfully to the expansion. Brazil\'s economic diversification, including a growing technology sector and expanding manufacturing base, has reduced commodity cycle sensitivity compared to a decade ago.',
        'Inflation of 4.4% slightly exceeded the Banco Central do Brasil\'s 3% target (with a 1.5 percentage point tolerance band), prompting the central bank to reverse its 2023 easing cycle and raise the Selic rate. Food prices and administered prices drove the overshoot. Unemployment declined to 6.8%, reflecting labour market improvement, though informality remains high. The current account deficit widened to -3.0% of GDP, partly reflecting strong import demand for capital equipment amid the investment upturn.',
        'Government debt at 87% of GDP is elevated for an emerging market economy, and fiscal credibility has been a persistent market concern. The Lula government\'s fiscal framework, centered on a structural primary surplus target, has been questioned by markets when spending growth exceeded stated commitments. Interest rates remain structurally high in Brazil compared to peer emerging markets, reflecting sovereign risk premiums and monetary policy transmission inefficiencies. R&D at 1.19% of GDP and health at 9.7% of GDP reflect Brazil\'s social investment priorities.',
        'Brazil\'s Gini coefficient of 50.3 is the second-highest in the G20 (after South Africa\'s 54.1), reflecting deep structural inequality rooted in historical patterns of land concentration, differential educational access, and labour market segmentation. Reducing inequality requires sustained investment in early childhood education, vocational training, and land tenure reform. Near-term risks include a deterioration of fiscal credibility, commodity price volatility, and El Niño-related agricultural disruptions. Upside potential lies in Brazil\'s enormous natural resources, energy diversification, and the expansion of its digital economy.',
      ],
    },

    CAN: {
      headline: 'Soft landing achieved, but housing, fiscal burden, and US trade exposure demand attention',
      paragraphs: [
        'Canada grew 1.6% in 2024, below its potential rate, as the Bank of Canada\'s cumulative 475 basis points of tightening restrained household consumption and housing market activity. GDP reached $2.24 trillion. Business investment outside the energy sector remained subdued, and housing construction fell from elevated levels. However, strong population growth from immigration, Canada admitted a record number of permanent residents, supported aggregate consumption and labour supply, partially offsetting the monetary tightening effect.',
        'Inflation eased to 2.4% in 2024, within the Bank of Canada\'s 1-3% target range, enabling the central bank to begin an easing cycle. Unemployment rose to 6.4%, the highest since 2017 excluding the pandemic period, reflecting labour market softening as hiring growth decelerated. GDP per capita of $54,000 reflects Canada\'s high-income status. Health spending at 11.3% of GDP and R&D at 1.79% of GDP are broadly reflective of a mature social democratic economy, though R&D intensity lags the United States and Germany.',
        'Government debt at 110% of GDP reflects pandemic-era fiscal expansion and ongoing social spending commitments. Canada\'s current account is near balance (-0.5% GDP), reflecting the offsetting effects of commodity exports (oil and gas, potash, lumber) and services imports. Housing affordability has emerged as an acute structural challenge, particularly in major urban markets, constraining labour mobility and household formation. Gini at 31.5 is relatively low, reflecting Canada\'s redistributive tax-and-transfer system.',
        'Canada\'s primary structural risk is trade concentration: approximately 75% of merchandise exports are destined for the United States, creating exceptional sensitivity to US trade policy shifts. Tariff threats and Buy American provisions create direct exposure. Diversifying trade relationships, particularly toward Asia-Pacific partners, is a strategic priority articulated in trade policy documents but not yet reflected in trade flow rebalancing. Nearshoring opportunities and energy transition investments (critical minerals, clean hydrogen) represent genuine medium-term growth opportunities for Canada\'s resource-rich economy.',
      ],
    },

    RUS: {
      headline: 'Wartime expansion masking structural fragilities; inflation and sanctions constraints intensify',
      paragraphs: [
        'Russia\'s economy expanded 4.9% in 2024, sustained by elevated defence expenditure, public investment, and suppressed import demand under western sanctions. GDP reached $2.17 trillion, a figure that partially reflects ruble appreciation effects. The composition of growth is structurally distorted: defence manufacturing, state-directed infrastructure, and energy production drove the expansion, while consumer and investment goods sectors remained constrained by import restrictions and capital outflows.',
        'Inflation accelerated to 8.4% in 2024, the highest in the G20 excluding Argentina and Türkiye, driven by fiscal stimulus, labour shortages as military mobilisation withdrew workers from civilian sectors, and supply-side constraints from import restrictions. Unemployment fell to 2.4%, the lowest in the G20, though this reflects labour market tightness under wartime conditions rather than structural economic health. The Central Bank of Russia maintained an aggressive tightening posture, raising rates to 21%, but the transmission of monetary policy is impaired by the dominant role of state-directed lending.',
        'Government debt at just 15% of GDP is the lowest in the G20, reflecting historically conservative fiscal management and substantial oil and gas revenues before 2022. National Wealth Fund reserves have been partially drawn down to finance fiscal deficits. The current account surplus of 2.9% of GDP reflects the partial redirection of energy exports toward China, India, and other non-sanctioning markets. Gross government R&D at 0.94% of GDP understates total investment but is below advanced economy peers.',
        'The medium-term outlook is shaped by escalating structural fragilities rather than near-term cyclical dynamics. Technology import restrictions limit production in advanced manufacturing, aviation, and electronics. Capital flight and brain drain reduce the economy\'s human capital stock. Dependence on commodity revenues creates fundamental vulnerability to oil price cycles. Sustainable civilian economic development requires resolution of geopolitical constraints that, absent a peace settlement, appear unlikely to be lifted in the near term.',
      ],
    },

    KOR: {
      headline: 'Technology-intensive economy normalises; world-leading R&D investment a structural advantage',
      paragraphs: [
        'South Korea grew 2.0% in 2024, a moderate recovery driven by a semiconductor export cycle upturn, resilient domestic consumption, and services sector expansion. GDP reached $1.88 trillion. The memory semiconductor industry, dominated by Samsung Electronics and SK Hynix, experienced a meaningful recovery in global demand and pricing following the 2023 downturn, providing a cyclical tailwind. Korea\'s economy is highly integrated into global technology value chains, making it acutely sensitive to semiconductor cycle dynamics.',
        'Inflation moderated to 2.3% in 2024, near the Bank of Korea\'s 2% target, enabling a cautious easing cycle. Unemployment at 2.8% is near structural lows. GDP per capita of $36,000 reflects South Korea\'s transition to a high-income economy over the past four decades, a development transformation unparalleled in modern economic history. South Korea\'s R&D investment of 4.94% of GDP is the highest in the G20 by a significant margin (second-highest is the United States at 3.45%), reflecting the economy\'s deep commitment to technology-intensive industrial specialisation.',
        'The current account surplus of 5.3% of GDP reflects strong technology export performance partially offset by energy import dependence (Korea imports approximately 95% of its energy needs). Government debt at 50% of GDP provides fiscal space. Health spending at 8.7% of GDP is below European peers, reflecting the relative youth of Korea\'s social protection system. Gini at 32.9 is moderate by G20 standards.',
        'Korea\'s primary structural risks are the economy\'s concentration in a narrow set of export sectors, semiconductors, automotive, and petrochemicals, and its demographic trajectory: Korea has one of the lowest birth rates in the world, with total fertility below 1.0, creating long-run labour supply constraints. Diversification toward platform economy, clean energy technology, and biosciences is underway but requires sustained investment. US-China technology decoupling creates both opportunity (supply chain shifts away from China) and risk (demand side exposure if China growth slows).',
      ],
    },

    AUS: {
      headline: 'Commodity-backed resilience, but below-trend growth as rate cycle bites',
      paragraphs: [
        'Australia grew 1.0% in 2024, below its estimated potential growth rate of around 2.5%, as the Reserve Bank of Australia\'s cumulative rate increases restrained household consumption and residential construction. GDP reached $1.80 trillion. Despite the cyclical slowdown, Australia avoided recession, reflecting the buffering role of strong commodity export revenues (iron ore, coal, LNG), resilient labour markets, and high levels of net immigration supporting aggregate demand.',
        'Inflation eased to 3.2% in 2024, still above the RBA\'s 2-3% target, with services inflation proving stickier than goods price disinflation. Unemployment held at 4.0%, near historical lows. GDP per capita of $64,000 is among the highest in the G20, reflecting Australia\'s resource wealth and high-income economy status. The current account deficit of -2.2% of GDP reflects domestic investment needs exceeding national savings, though this has been financed comfortably.',
        'Gross government debt at 51% of GDP is among the lowest in the G20 advanced economies, reflecting Australia\'s generally conservative fiscal tradition and the structural support provided by mining royalties and related revenues. Health spending at 10.4% of GDP is in line with OECD peers. R&D at 1.86% of GDP is below the frontier, reflecting Australia\'s economic concentration in lower-technology primary industries. Gini at 33.8 reflects moderate inequality by international standards.',
        'Australia\'s primary structural risk is trade concentration in China, which absorbs approximately 30% of Australian exports, primarily iron ore, coal, and LNG. A sharper-than-expected Chinese growth slowdown or commodity demand deceleration poses a terms-of-trade risk. Diversifying toward higher-value-added manufacturing and services exports is a strategic priority. Near-term opportunities include critical minerals for the energy transition (lithium, cobalt, rare earths), clean energy exports, and defence manufacturing as the AUKUS partnership expands.',
      ],
    },

    MEX: {
      headline: 'Nearshoring opportunity offsets below-potential growth; structural investment gap persists',
      paragraphs: [
        'Mexico grew 1.4% in 2024, below its potential, as elevated domestic borrowing costs and policy uncertainty weighed on private investment. GDP reached $1.86 trillion, a significant achievement for Latin America\'s second-largest economy. Manufacturing output, particularly in automotive and electronics, remained robust, supported by strong US demand and the nearshoring wave of US-China supply chain diversification. Mexico\'s proximity to the United States and USMCA trade framework position it as a principal beneficiary of this structural shift.',
        'Inflation of 4.7% exceeded the Banco de Mexico\'s 3% target, constraining the space for rate cuts despite softening growth. Unemployment remained exceptionally low at 2.7%, one of the lowest in the G20, reflecting Mexico\'s labour-intensive manufacturing base and large informal sector. GDP per capita of $14,000 places Mexico in the upper-middle-income range. The current account deficit of -0.9% of GDP is modest and manageable.',
        'Gross government debt at 59% of GDP is moderate, though fiscal pressures have been elevated by energy sector subsidies and spending on social programmes. R&D at 0.25% of GDP is the second-lowest in the G20, reflecting Mexico\'s chronic underinvestment in innovation and human capital relative to its development aspirations. Health spending at 5.5% of GDP is also below comparators. Gini at 42.6 reflects significant inequality, with structural barriers limiting social mobility despite strong labour market outcomes at the aggregate level.',
        'Mexico\'s primary strategic opportunity is maximising the nearshoring dividend by upgrading infrastructure, improving rule of law and security, and investing in skills to shift up value chains beyond assembly manufacturing. US tariff risk is a double-edged exposure: Mexico is vulnerable to tariff escalation but also benefits when US tariffs on China redirect supply chain investment toward North American manufacturing. Water scarcity, particularly in the industrialising north, is an emerging constraint on further manufacturing expansion. Near-term political risk diminished following the 2024 presidential election.',
      ],
    },

    IDN: {
      headline: 'Joint-fastest growing major economy; infrastructure and human capital are the development priorities',
      paragraphs: [
        'Indonesia matched China as the fastest-growing among the larger G20 economies in 2024, posting 5.0% real GDP growth. GDP reached $1.40 trillion, the sixteenth-largest in the G20. Domestic consumption, underpinned by a young and growing population of over 280 million, remained the primary growth engine, supplemented by public infrastructure investment, a growing digital economy, and expanding manufactured exports. Indonesia has consistently delivered stable, broad-based growth since the 1997-1998 Asian financial crisis, reflecting institutional consolidation and macro-policy discipline.',
        'Inflation of 2.2% was within Bank Indonesia\'s 1.5-3.5% target range, one of the lowest inflation readings in the G20 despite strong demand growth. Unemployment at 4.9% reflects the ILO modelled estimate, above the lower official BPS survey rate. The current account deficit narrowed to -0.6% of GDP. Government debt at 40% of GDP is the second-lowest in the G20, providing substantial fiscal space. GDP per capita of just $4,000 underscores Indonesia\'s development-stage position and the enormous catch-up potential ahead.',
        'R&D investment at 0.28% of GDP and health spending at 2.7% of GDP are the lowest in the G20, reflecting the structural underinvestment in human capital and innovation infrastructure that constrains productivity convergence. While Indonesia\'s aggregate growth is impressive, the quality of that growth, measured by productivity per worker, requires sustained upgrading through education, skills, and technological capability development. The transition from commodity dependence (palm oil, coal, nickel) toward manufacturing and services exports is underway but incomplete.',
        'Indonesia\'s most significant strategic asset is its dominant position in nickel, it holds approximately 40% of global reserves, positioning it centrally in the electric vehicle battery supply chain. A domestic processing requirement has attracted major battery and EV manufacturers. Near-term risks include commodity price volatility, climate-related disruptions to agriculture and coastal infrastructure, and the fiscal and governance challenges of managing the infrastructure investment programme at scale. Longstanding regulatory barriers to foreign investment, if reduced, could significantly accelerate capital inflows.',
      ],
    },

    SAU: {
      headline: 'Non-oil diversification advances under Vision 2030; oil constraints limit headline growth',
      paragraphs: [
        'Saudi Arabia grew 2.0% in 2024, a deceleration from 2023, as OPEC+ production cuts limited oil output and suppressed the petroleum sector\'s contribution to GDP growth. GDP reached $1.24 trillion. Non-oil GDP grew considerably faster, driven by Vision 2030 megaprojects, tourism expansion, entertainment sector development, and financial services growth. The government\'s ambitious transformation programme, centred on reducing oil dependence and creating a diversified private sector economy, is delivering measurable, if uneven, progress.',
        'Inflation was minimal at 1.7%, the second-lowest in the G20 after China, reflecting the Saudi riyal\'s peg to the US dollar (which imports US monetary policy) and administered energy and food prices. Unemployment at 3.5% masks structural labour market features: the Kingdom has been pursuing localisation (Saudisation) of private sector employment to reduce dependence on expatriate labour, with significant implications for labour costs and sector competitiveness. GDP per capita of $35,000 places Saudi Arabia among upper-income economies.',
        'Government debt at 26% of GDP is very low, and Saudi Arabia\'s substantial sovereign wealth fund (Public Investment Fund, with assets exceeding $700 billion) provides significant fiscal buffer. The current account moved to a slight deficit (-1.3% GDP) in 2024 as lower oil prices reduced export revenues while domestic investment spending, particularly on Vision 2030 megaprojects, accelerated. R&D investment at 0.64% of GDP remains below the innovation frontier, reflecting the economy\'s early-stage technology development.',
        'The long-run strategic challenge for Saudi Arabia is calibrating the pace of transformation with the fiscal requirements of managing the energy transition globally. If oil demand peaks sooner than official projections, the window for monetising reserves and investing the proceeds into a diversified knowledge economy narrows. Near-term risks include oil price volatility driven by global demand conditions and geopolitical dynamics in the Middle East. Continued improvement in institutional quality, rule of law, and entrepreneurship climate is essential for Vision 2030 objectives to be met.',
      ],
    },

    ARG: {
      headline: 'Stabilisation underway after macroeconomic emergency; disinflation is real but costly',
      paragraphs: [
        'Argentina\'s economy contracted 1.3% in 2024 as the Milei administration implemented the most dramatic fiscal adjustment in the country\'s modern history. GDP reached $0.64 trillion, a figure substantially distorted by the peso\'s multi-rate exchange system. The programme\'s centrepiece, eliminating the primary fiscal deficit in a single year through public spending cuts exceeding 5% of GDP, was achieved, generating significant near-term economic pain but establishing a credibility foundation absent from Argentine economic policy for decades. GDP per capita of $13,000 reflects a middle-income economy severely impaired by macroeconomic mismanagement.',
        'Consumer price inflation of 219.9% is the highest in the G20 by a very wide margin, a macroeconomic emergency by any measure. However, the monthly trajectory was more encouraging: inflation decelerated from over 25% per month at the programme\'s start to approximately 3-4% per month by late 2024 as the fiscal anchor took hold and the peso was stabilised through a managed crawling peg. Unemployment rose to 7.2% as the public sector contracted and private demand fell. The current account turned positive (+0.9% GDP), reflecting compressed import demand.',
        'Gross government debt at 85% of GDP, combined with limited access to international capital markets following multiple sovereign defaults, defines the binding constraint on Argentine fiscal policy. The IMF extended programme requires consistent primary surplus delivery. Argentina\'s Gini of 42.4 reflects significant inequality that worsened through the 2024 adjustment, as real wages fell sharply in the first half of the year. Health spending at 10.3% of GDP reflects public system coverage that has been partly protected despite broader austerity.',
        'The stabilisation programme\'s success hinges on the durability of the fiscal adjustment as political and social pressures mount, the ability to recapitalise central bank reserves, and the eventual lifting of capital controls that limit exchange rate normalisation. If maintained, the programme could represent the beginning of a genuine macroeconomic turning point after decades of recurring crises. Failure would mean another disorderly default cycle with severe social consequences. Argentina\'s commodity wealth, agricultural commodities and the world\'s second-largest lithium reserves, provides an underlying resource base for medium-term recovery if governance conditions permit.',
      ],
    },

    TUR: {
      headline: 'Policy normalisation credible but disinflation will be prolonged',
      paragraphs: [
        'Turkey grew 3.3% in 2024 despite one of the most aggressive monetary tightening cycles in its history, a notable demonstration of the economy\'s underlying dynamism. GDP reached $1.36 trillion. Growth was driven by private consumption (partly frontloaded ahead of expected disinflation) and export services including tourism. The government completed a policy U-turn from the unorthodox low-rate experiment of 2021-2023, installing a conventional central bank leadership team and raising the policy rate from 8.5% to 50% between 2023 and 2024.',
        'Consumer price inflation of 58.5% in 2024 is the highest in the G20 after Argentina, a reflection of the accumulated price inertia from years of monetary policy misalignment, lira depreciation, and expansionary fiscal policy. Disinflation is underway but will be gradual: Turkey\'s structural inflation drivers include indexed wages, dollarised pricing in real estate and durables, and supply chain vulnerabilities. Unemployment at 8.8% is above the G20 median. Gini at 43.7 reflects significant inequality.',
        'Government debt at 24% of GDP is very low by international standards, providing fiscal space. The current account deficit of -0.8% of GDP has narrowed significantly from prior years as import compression and tourism revenues improved. GDP per capita of $15,000 positions Turkey as an upper-middle-income economy with significant development potential. R&D at 1.42% of GDP reflects growing Turkish defence industry and technology sector investment.',
        'Turkey\'s medium-term outlook depends critically on completing the disinflation programme while sustaining adequate growth. Risks include geopolitical disruptions (Turkey\'s complex position between NATO, Russia, and the Middle East), lira volatility reigniting inflation expectations, and political pressures challenging central bank independence. The positive case rests on Turkey\'s young population, strategic geographic position for energy transit and trade, growing industrial capability, and the anchoring effect of the normalisation programme if sustained.',
      ],
    },

    ZAF: {
      headline: 'Unemployment crisis and infrastructure failures constrain a resource-rich economy',
      paragraphs: [
        'South Africa posted 0.5% growth in 2024, the weakest in the G20, as persistent electricity shortages (load shedding reaching up to Stage 6 rationing), logistics network failures, and subdued investor confidence constrained economic activity. GDP reached $0.40 trillion, the smallest in the G20. Manufacturing and mining output were particularly impacted by unreliable power supply from the state electricity utility Eskom, whose installed capacity has declined through years of governance failures and maintenance neglect.',
        'Inflation moderated to 4.4% in 2024, within the South African Reserve Bank\'s 3-6% target range, enabling cautious monetary easing. However, structural inflation drivers, including administered utility prices (electricity, water) and food price volatility, remain. Unemployment at 32.3% is the highest in the G20 by a dramatic margin, South Africa\'s labour market crisis is of structural, not cyclical, origin, rooted in skills mismatches, labour market rigidities, spatial economic segregation inherited from apartheid, and insufficient formal sector job creation relative to labour force growth.',
        'Government debt at 76% of GDP is rising, driven by persistent primary deficits and below-potential growth. Contingent liabilities from state-owned enterprises (particularly Eskom\'s debt, partially transferred to the national balance sheet) represent additional fiscal risk. R&D at 0.61% of GDP and health at 8.9% of GDP represent meaningful investment levels relative to the economy\'s size, though both face efficiency challenges. The Gini coefficient of 54.1 makes South Africa the most unequal economy in the G20, a structural legacy of apartheid-era spatial and economic segregation that constrains social cohesion and human capital development.',
        'The near-term priority is infrastructure rehabilitation: resolving the electricity supply crisis through accelerated private sector generation licensing and Eskom operational reform, and fixing port and rail logistics network failures that impair mining exports. Success on these fronts could add 1-2 percentage points to potential growth without new fiscal commitments. Longer-term, reducing structural unemployment requires comprehensive education reform, active labour market policies, reducing barriers to entrepreneurship, and addressing spatial economic inequalities that limit access to economic opportunity. South Africa\'s mineral wealth, gold, platinum group metals, manganese, chrome, provides a structural export foundation, but realising this potential requires the infrastructure and governance conditions to attract sustained investment.',
      ],
    },

  },
};
