// AUTO-GENERATED by sync/train-forecast.js — do not edit by hand.
// Trained 2026-05-31 on 434 country-year pairs. LOYO-CV AUC 0.538, growth RMSE 3.42pp.
window.G20_MODEL = {
  "features": [
    "GROWTH",
    "MOMENTUM",
    "FISCAL_BAL",
    "DEBT_GDP",
    "CURRENT_ACC",
    "UNEMPLOYMENT",
    "INFLATION"
  ],
  "recession": {
    "coef": [
      -0.5714454070607171,
      0.10242704901969699,
      0.537895545293704,
      0.25191400829500776,
      -0.2775495488892245,
      -0.21795091670601263,
      0.15390321139933077
    ],
    "intercept": -2.1479035250100544,
    "mu": [
      2.9483870967741943,
      -0.09193548387096777,
      -2.9529953917050675,
      66.83041474654377,
      0.5852534562211982,
      7.671539170506908,
      5.9596774193548425
    ],
    "sigma": [
      3.642188747607348,
      4.561490220103045,
      4.306527332268221,
      43.59178881282253,
      4.891039870897524,
      5.302609092130924,
      14.488064717234668
    ]
  },
  "growth": {
    "coef": [
      1.8136913547354396,
      -0.8244065719884325,
      -1.3624634428229279,
      -0.6253698293513478,
      1.058954453346888,
      0.202632630416254,
      0.07257499693132759
    ],
    "intercept": 2.9430875576036866,
    "mu": [
      2.9483870967741943,
      -0.09193548387096777,
      -2.9529953917050675,
      66.83041474654377,
      0.5852534562211982,
      7.671539170506908,
      5.9596774193548425
    ],
    "sigma": [
      3.642188747607348,
      4.561490220103045,
      4.306527332268221,
      43.59178881282253,
      4.891039870897524,
      5.302609092130924,
      14.488064717234668
    ]
  },
  "meta": {
    "trainedAt": "2026-05-31",
    "n": 434,
    "baseRate": 0.1198,
    "recAUC": 0.538,
    "growthRMSE": 3.42,
    "growthPersistenceRMSE": 4.16,
    "growthBeatsPersistence": 0.74,
    "horizonYears": 1,
    "notes": "Logistic (recession) + ridge (growth), 1-year-ahead, pooled G20 panel 2000-2025. Metrics are leave-one-year-out cross-validated. Recession label is GFC-2009 / COVID-2020 heavy: read as a model-implied relative probability, not a calibrated event probability."
  }
};
