// AUTO-GENERATED by sync/train-forecast.js — do not edit.
window.G20_MODEL = {
  "fundFeatures": [
    "GROWTH",
    "MOMENTUM",
    "FISCAL_BAL",
    "DEBT_GDP",
    "CURRENT_ACC",
    "UNEMPLOYMENT",
    "INFLATION"
  ],
  "recFeatures": [
    "GROWTH",
    "MOMENTUM",
    "FISCAL_BAL",
    "DEBT_GDP",
    "CURRENT_ACC",
    "UNEMPLOYMENT",
    "INFLATION",
    "TERM_SPREAD"
  ],
  "growth": {
    "coef": [
      1.8136913547354396,
      -0.8244065719884325,
      -1.3624634428229279,
      -0.6253698293513478,
      1.058954453346888,
      0.202632630416254,
      0.07257499693132759
    ],
    "intercept": 2.9430875576036866,
    "mu": [
      2.9483870967741943,
      -0.09193548387096777,
      -2.9529953917050675,
      66.83041474654377,
      0.5852534562211982,
      7.671539170506908,
      5.9596774193548425
    ],
    "sigma": [
      3.642188747607348,
      4.561490220103045,
      4.306527332268221,
      43.59178881282253,
      4.891039870897524,
      5.302609092130924,
      14.488064717234668
    ]
  },
  "recession": {
    "coef": [],
    "intercept": 0,
    "mu": [],
    "sigma": [],
    "covered": [],
    "auc": null,
    "aucCyclical": null,
    "gate": 0.65
  },
  "backtest": [
    {
      "forecastYear": 2003,
      "growthRMSE": 3.24,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2004,
      "growthRMSE": 2.93,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2005,
      "growthRMSE": 2.94,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2006,
      "growthRMSE": 2.45,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2007,
      "growthRMSE": 2.56,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2008,
      "growthRMSE": 1.74,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2009,
      "growthRMSE": 6.09,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2010,
      "growthRMSE": 4.06,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2011,
      "growthRMSE": 2.72,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2012,
      "growthRMSE": 1.7,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2013,
      "growthRMSE": 1.86,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2014,
      "growthRMSE": 1.94,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2015,
      "growthRMSE": 2.18,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2016,
      "growthRMSE": 2.08,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2017,
      "growthRMSE": 1.94,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2018,
      "growthRMSE": 1.75,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2019,
      "growthRMSE": 1.59,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2020,
      "growthRMSE": 7.76,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2021,
      "growthRMSE": 7.4,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2022,
      "growthRMSE": 2.64,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2023,
      "growthRMSE": 2.27,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2024,
      "growthRMSE": 2.16,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2025,
      "growthRMSE": 1.87,
      "recessions": 0,
      "recHits": 0
    }
  ],
  "meta": {
    "trainedAt": "2026-06-01",
    "nGrowth": 434,
    "nRecession": 0,
    "growthRMSE": 3.42,
    "growthPersistenceRMSE": 4.16,
    "growthBeatsPersistence": 0.74,
    "recAUC": null,
    "recAUCCyclical": null,
    "horizonYears": 1,
    "notes": "Growth: ridge, pooled G20 (beats persistence). Recession model disabled — no yield-curve term spread available in the data."
  }
};
