// AUTO-GENERATED by sync/train-forecast.js — do not edit.
window.G20_MODEL = {
  "fundFeatures": [
    "GROWTH",
    "MOMENTUM",
    "FISCAL_BAL",
    "DEBT_GDP",
    "CURRENT_ACC",
    "UNEMPLOYMENT",
    "INFLATION"
  ],
  "recFeatures": [
    "GROWTH",
    "MOMENTUM",
    "FISCAL_BAL",
    "DEBT_GDP",
    "CURRENT_ACC",
    "UNEMPLOYMENT",
    "INFLATION",
    "TERM_SPREAD"
  ],
  "growth": {
    "coef": [
      1.8136913547354396,
      -0.8244065719884325,
      -1.3624634428229279,
      -0.6253698293513478,
      1.058954453346888,
      0.202632630416254,
      0.07257499693132759
    ],
    "intercept": 2.9430875576036866,
    "mu": [
      2.9483870967741943,
      -0.09193548387096777,
      -2.9529953917050675,
      66.83041474654377,
      0.5852534562211982,
      7.671539170506908,
      5.9596774193548425
    ],
    "sigma": [
      3.642188747607348,
      4.561490220103045,
      4.306527332268221,
      43.59178881282253,
      4.891039870897524,
      5.302609092130924,
      14.488064717234668
    ]
  },
  "recession": {
    "coef": [
      -0.48763197460684654,
      0.032891449729864304,
      0.5971000367222025,
      0.519681351534743,
      -0.06404588565426067,
      0.040861561599292245,
      0.15366786921511627,
      -0.48082945274922995
    ],
    "intercept": -2.19351154719172,
    "mu": [
      1.8303703703703704,
      -0.1977777777777777,
      -2.972592592592593,
      76.11777777777777,
      0.1618518518518519,
      7.679629629629631,
      3.0874074074074085,
      0.983062962962963
    ],
    "sigma": [
      2.7549490571098096,
      3.9135087347908075,
      3.343161724401124,
      48.26624825887809,
      3.5861859829041287,
      6.352887346758445,
      2.7369875202256697,
      1.323592451443097
    ],
    "covered": [
      "AUS",
      "CAN",
      "DEU",
      "FRA",
      "GBR",
      "ITA",
      "JPN",
      "KOR",
      "MEX",
      "RUS",
      "USA",
      "ZAF"
    ],
    "auc": 0.527,
    "aucCyclical": 0.578,
    "gate": 0.65
  },
  "backtest": [
    {
      "forecastYear": 2003,
      "growthRMSE": 3.24,
      "recessions": 1,
      "recHits": 0
    },
    {
      "forecastYear": 2004,
      "growthRMSE": 2.93,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2005,
      "growthRMSE": 2.94,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2006,
      "growthRMSE": 2.45,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2007,
      "growthRMSE": 2.56,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2008,
      "growthRMSE": 1.74,
      "recessions": 2,
      "recHits": 0
    },
    {
      "forecastYear": 2009,
      "growthRMSE": 6.09,
      "recessions": 10,
      "recHits": 0
    },
    {
      "forecastYear": 2010,
      "growthRMSE": 4.06,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2011,
      "growthRMSE": 2.72,
      "recessions": 1,
      "recHits": 0
    },
    {
      "forecastYear": 2012,
      "growthRMSE": 1.7,
      "recessions": 1,
      "recHits": 0
    },
    {
      "forecastYear": 2013,
      "growthRMSE": 1.86,
      "recessions": 1,
      "recHits": 0
    },
    {
      "forecastYear": 2014,
      "growthRMSE": 1.94,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2015,
      "growthRMSE": 2.18,
      "recessions": 1,
      "recHits": 0
    },
    {
      "forecastYear": 2016,
      "growthRMSE": 2.08,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2017,
      "growthRMSE": 1.94,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2018,
      "growthRMSE": 1.75,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2019,
      "growthRMSE": 1.59,
      "recessions": 2,
      "recHits": 0
    },
    {
      "forecastYear": 2020,
      "growthRMSE": 7.76,
      "recessions": 11,
      "recHits": 0
    },
    {
      "forecastYear": 2021,
      "growthRMSE": 7.4,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2022,
      "growthRMSE": 2.64,
      "recessions": 0,
      "recHits": 0
    },
    {
      "forecastYear": 2023,
      "growthRMSE": 2.27,
      "recessions": 1,
      "recHits": 0
    },
    {
      "forecastYear": 2024,
      "growthRMSE": 2.16,
      "recessions": 2,
      "recHits": 0
    },
    {
      "forecastYear": 2025,
      "growthRMSE": 1.87,
      "recessions": 0,
      "recHits": 0
    }
  ],
  "meta": {
    "trainedAt": "2026-07-24",
    "nGrowth": 434,
    "nRecession": 270,
    "growthRMSE": 3.42,
    "growthMAE": 2.35,
    "growthPersistenceRMSE": 4.16,
    "growthBeatsPersistence": 0.74,
    "recAUC": 0.527,
    "recAUCCyclical": 0.578,
    "recAUCFundamentalsOnly": 0.494,
    "horizonYears": 1,
    "notes": "Growth: ridge, pooled G20. Recession: logistic on yield-curve-covered economies (term spread 10y-3m, keyless FRED). LOYO-CV. Recession probability framed as cyclical (AUC 0.58); all-period 0.53 reflects the unpredictable 2020 pandemic."
  }
};
